# 后台标签页列表
import os
DEBUG = True
ADMIN_TAG_PAGE=5
ADMIN_MOVIE_PAGE=5
ADMIN_PREVIEW_PAGE=5
ADMIN_USER_PAGE=5
ADMIN_COMMENT_PAGE=5
ADMIN_MOVIECOL_PAGE=5
ADMIN_OPLOG_PAGE=5
ADMIN_ADMINLOGINLOG_PAGE=5
ADMIN_USERLOGINLOG_PAGE=5
ADMIN_AUTH_PAGE=5
ADMIN_ROLE_PAGE=5
ADMIN_ADMIN_PAGE=5
HOME_MOVIE_PAGE=12
HOME_SEARCH_PAGE=5
HOME_COMMENT_PAGE=5
HOME_MOVIECOL_PAGE=5

UPLOADED_DIR='uploads'
UPLOADED_PATH=os.path.join(os.path.abspath(os.path.dirname(__file__)),'../static/')
SECRET_KEY = os.urandom(24)
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:123456@192.168.100.29:3306/movie'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_TEARDOWN = True